services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: aprendegame/app:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_HOST: db
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - aprendegame_storage:/var/www/html/storage
    networks:
      - aprendegame_net

  web:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8002:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - aprendegame_storage:/var/www/html/storage
    networks:
      aprendegame_net: # era: aprendegame_net


  horizon:
    image: aprendegame/app:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_HOST: db
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: ["php", "artisan", "horizon"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - aprendegame_storage:/var/www/html/storage
    networks:
      - aprendegame_net

  scheduler:
    image: aprendegame/app:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_HOST: db
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: ["sh", "-lc", "while true; do php artisan schedule:run --no-interaction; sleep 60; done"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - aprendegame_storage:/var/www/html/storage
    networks:
      - aprendegame_net

  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - aprendegame_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - aprendegame_net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - aprendegame_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - aprendegame_net

networks:
  aprendegame_net:
    driver: bridge

volumes:
  aprendegame_storage:
  aprendegame_db:
  aprendegame_redis:
